export const COLLECTIONS = {
  BANNER: 'BANNER',
  CARD: 'CARD',
  EVENT: 'EVENT',
  CREDIT: 'CREDIT',
  TERMS: 'TERMS',
  ACCOUNT: 'ACCOUNT',
  TRANSACTION: 'TRANSACTION',
  PIGGYBANK: 'PIGGYBANK',
  FAQ: 'FAQ',
} as const;
