yarnPath: .yarn/releases/yarn-4.1.0.cjs

packageExtensions:
  "local-pkg@*":
    dependencies:
      "happy-dom": "^13.6.0"
  "swiper@*":
    dependencies:
      "react": "^18.0.2"
  "@aws-sdk/core@*":
    dependencies:
      "tslib": "*"
  "react-intersection-observer@*":
    dependencies:
      "react-dom": "*"
